### ISSUE TITLE
First exercise relies on concepts not yet introduced

### ISSUE THREAD

**Issue by kholbekj** [SquareBracketAssociates/NewPharoByExample9#16]
Going through the book, the first exercise:

```
The setter method does not currently exist, so as an exercise create the method ==count:== such that, when invoked on an
instance of ==Counter==, the instance variable is set to the argument of the message. Test your method by evaluating the
example above in a Playground.
```
Was not solvable for me without google (which lead to a smalltalk thread of someone else asking the same question).
- The fact that we can pass arguments to methods in definitions (`count: someValue`)
- The fact that we can assign to our own instance variables by simple name (`count := someValue`)

are both new concepts at this point that haven't been described, so the exercise doesn't really test our knowledge, but rather forces us to look for another resource to learn the syntax.

I'm happy to update it, but was wondering if you prefer:
- an explanation of these possibilities
- or a solution after the fact
- or something else?

**Comment by Ducasse** [comment]
Thanks for the feedback. This is super basic in fact :).
May be you can check Learning OOD with TDD in Pharo because this is more a beginner book and I may have made the same "difficulty" there.

**Comment by kholbekj** [comment]
Sure, it's basic. At the same time the book is also setting that stage by introducing the rest of the syntax. If the book is not meant to teach it, then maybe it should explicitly say so and refer to the other work?

It felt like a good introduction for someone proficient in other languages, but syntax is a hard thing to guess :D
